
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[291] =
    {   0,
        0,    0,  100,   98,   97,   97,   85,   98,    5,   91,
       84,   98,   79,   80,   89,   88,   76,   87,   83,   90,
       45,   45,   77,   73,   92,   78,   93,   96,   42,   42,
       81,   82,   94,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   74,
       95,   75,   86,   72,    0,   50,    0,    0,    0,    0,
       58,   75,   67,   59,    0,    0,   56,   64,   54,   65,
       55,   66,    0,   48,    1,   57,   49,   44,    0,   45,
        0,   45,   82,   74,   81,   63,   69,   71,   70,   62,
       42,    0,    0,   60,   42,   42,   42,   42,   42,   42,

       42,   15,   42,   42,   42,   42,   42,   42,   23,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       61,   68,    0,    0,    0,   46,   51,    0,   48,   48,
        0,   49,   44,    0,   47,   43,   53,   52,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   21,   42,   24,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,    0,    0,    0,    0,   48,    0,   48,    0,   49,
       47,   43,   42,   42,   42,   42,    8,   42,   10,   11,
       42,   42,   42,   42,   17,   18,   42,   42,   22,   25,

       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   37,   42,   42,    0,    2,    0,    0,   48,   42,
       42,   42,   42,    9,   12,   42,   42,   42,   42,   20,
       42,   42,   28,   42,   42,   42,   42,   42,   42,   35,
       42,   42,   39,    0,    0,   42,   42,   42,   42,   42,
       42,   16,   19,   42,   27,   29,   30,   31,   32,   33,
       42,   42,   42,    4,    0,   41,   42,   40,   42,   42,
       14,   42,   34,   42,   42,    3,   42,   42,   13,   26,
       36,   38,   42,   42,   42,    7,   42,   42,    6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   30,   29,   29,   29,   31,   29,   29,   32,   29,
       29,   33,   29,   34,   35,   29,   36,   37,   29,   29,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   29,   52,   53,   54,   55,
       56,   57,   29,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1,
        1,    4,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[295] =
    {   0,
        0,    0,  425,  426,  426,  426,  401,   66,   26,   51,
       68,  384,  426,  426,  399,   65,  426,   66,   64,   72,
       90,   83,  397,  426,   93,  397,   62,  426,    0,   87,
      426,  426,  396,  376,  356,  358,   76,   47,   67,   51,
      359,   80,  358,  366,   89,  347,  356,  354,  359,  426,
       56,  426,  426,  426,  106,  426,  405,  360,  353,  350,
      426,  426,  426,  426,   84,  138,  426,  426,  426,  426,
      426,  426,  388,  137,  426,  426,  139,  144,  159,  145,
        0,  177,  426,  426,  426,  380,  426,  426,  426,  379,
        0,  107,  362,  426,  168,  340,  352,  339,  354,  341,

      347,  333,  334,  331,  331,  334,  331,  328,    0,  327,
      331,   38,  329,   84,   95,  333,  326,   83,  108,  331,
      426,  426,  333,  321,  334,  426,  426,  201,  426,  204,
      221,  426,  168,  163,  225,  202,  426,  426,  348,  317,
      320,  328,  318,  330,  325,  313,  129,  327,  325,  321,
      313,  319,  322,    0,  308,    0,  314,  311,  300,  302,
      304,  311,  297,  295,  295,  307,  297,  301,  305,  307,
      296,  297,  300,  293,  182,  231,  251,  426,  191,  249,
      426,  230,  312,  284,  288,  283,    0,  289,    0,    0,
      280,  288,  277,  284,    0,    0,  278,  275,    0,    0,

      275,  275,  272,  284,  274,  278,  283,  282,  280,  270,
      275,    0,  263,  275,  266,  426,  255,  199,  257,  277,
      250,  248,  246,    0,    0,  249,  250,  254,  245,    0,
      239,  243,    0,  250,  247,  249,  233,  242,  243,    0,
      234,  236,    0,  239,  236,  245,  223,  212,  213,  199,
      198,    0,    0,  207,    0,    0,    0,    0,    0,    0,
      200,  200,  193,  426,  198,    0,  198,    0,  190,  181,
        0,  169,    0,  179,  168,  426,  146,  149,    0,    0,
        0,    0,  123,  113,  122,    0,  106,   87,    0,  426,
      310,  314,  316,   94

    } ;

static yyconst flex_int16_t yy_def[295] =
    {   0,
      290,    1,  290,  290,  290,  290,  290,  291,  290,  290,
      290,  292,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  293,  293,
      290,  290,  290,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  290,
      290,  290,  290,  290,  291,  290,  291,  290,  290,  290,
      290,  290,  290,  290,  292,  292,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      294,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      293,  291,  292,  290,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  294,  290,  290,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  290,  290,  290,  290,  290,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  290,  290,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  290,  290,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  290,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,    0,
      290,  290,  290,  290

    } ;

static yyconst flex_int16_t yy_nxt[497] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   29,
       30,   29,   29,   29,   29,   29,   29,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   29,
       42,   29,   43,   29,   29,   29,   29,   44,   45,   46,
       47,   48,   49,   29,   29,   29,   50,   51,   52,   53,
       56,   58,   59,   61,   62,   63,   60,   68,  121,   73,
       70,   74,   74,   75,   89,   90,  158,   69,   71,   72,
       64,   92,  126,  101,   76,   93,  136,  159,   77,   84,

       82,   82,  102,  106,   57,   77,  107,   78,   78,   79,
       56,   56,   85,   80,   86,   87,   79,   80,   98,  103,
       80,  104,   66,  122,   80,   99,   81,  109,  289,   79,
      105,  100,  161,  167,  110,   80,   79,  163,  113,  114,
      290,  168,   80,   80,   57,   57,   65,  288,  115,  162,
       80,  116,  164,   81,   74,   74,  130,  130,  169,   77,
      170,   78,   78,  128,  129,  131,  132,  129,  287,  132,
       79,  134,  286,  134,  133,   80,  135,  135,  133,   80,
      135,  135,  285,  128,  129,  131,  132,  191,  192,  129,
       79,  132,   77,  284,   82,   82,  133,   80,  133,  176,

      176,  139,  133,   79,  133,   80,  283,   80,  180,  180,
      140,   80,  141,  175,  282,  175,  219,  219,  176,  176,
      133,  130,  130,   79,  281,  142,  280,  279,  133,   80,
      177,  178,  182,  179,  178,  179,  182,   80,  180,  180,
      278,  277,  135,  135,  276,  275,  274,  273,  176,  176,
      177,  178,  181,  272,  182,  181,  178,  271,  129,  270,
      182,  129,  182,  218,  182,  218,  180,  180,  219,  219,
      269,  268,  181,  267,  219,  219,  132,  181,  129,  132,
      266,  265,  182,  129,  178,  264,  263,  178,  262,  261,
      182,  260,  259,  258,  257,  256,  132,  255,  254,  253,

      252,  132,  251,  250,  178,  249,  248,  247,  246,  178,
       55,   55,   55,   55,   65,  245,   65,   65,   91,   91,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      190,  189,  188,  187,  186,  185,  184,  183,  174,  173,
      172,  171,  166,  165,  160,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,

       66,  138,  137,  127,  125,  124,  123,  290,  120,  119,
      118,  117,  112,  111,  108,   97,   96,   95,   94,   88,
       83,   67,   66,   54,  290,    3,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290

    } ;

static yyconst flex_int16_t yy_chk[497] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,    9,    9,   10,   10,   11,    9,   16,   51,   19,
       18,   19,   19,   20,   27,   27,  112,   16,   18,   18,
       11,   30,   65,   38,   20,   30,  294,  112,   22,   25,

       22,   22,   38,   40,    8,   21,   40,   21,   21,   22,
       55,   92,   25,   22,   25,   25,   21,   22,   37,   39,
       21,   39,   65,   51,   21,   37,   21,   42,  288,   22,
       39,   37,  114,  118,   42,   22,   21,  115,   45,   45,
       66,  118,   21,   22,   55,   92,   66,  287,   45,  114,
       21,   45,  115,   21,   74,   74,   77,   77,  119,   78,
      119,   78,   78,   74,   74,   77,   77,   74,  285,   77,
       78,   79,  284,   79,   78,   80,   79,   79,   78,   80,
      134,  134,  283,   74,   74,   77,   77,  147,  147,   74,
       78,   77,   82,  278,   82,   82,   78,   80,  133,  175,

      175,   95,  133,   82,   78,   80,  277,   82,  179,  179,
       95,   82,   95,  128,  275,  128,  218,  218,  128,  128,
      133,  130,  130,   82,  274,   95,  272,  270,  133,   82,
      130,  130,  136,  131,  130,  131,  136,   82,  131,  131,
      269,  267,  135,  135,  265,  263,  262,  261,  176,  176,
      130,  130,  135,  254,  136,  135,  130,  251,  176,  250,
      182,  176,  136,  177,  182,  177,  180,  180,  177,  177,
      249,  248,  135,  247,  219,  219,  180,  135,  176,  180,
      246,  245,  182,  176,  219,  244,  242,  219,  241,  239,
      182,  238,  237,  236,  235,  234,  180,  232,  231,  229,

      228,  180,  227,  226,  219,  223,  222,  221,  220,  219,
      291,  291,  291,  291,  292,  217,  292,  292,  293,  293,
      215,  214,  213,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  198,  197,  194,  193,  192,  191,
      188,  186,  185,  184,  183,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  155,  153,  152,  151,  150,  149,  148,
      146,  145,  144,  143,  142,  141,  140,  139,  125,  124,
      123,  120,  117,  116,  113,  111,  110,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,

       93,   90,   86,   73,   60,   59,   58,   57,   49,   48,
       47,   46,   44,   43,   41,   36,   35,   34,   33,   26,
       23,   15,   12,    7,    3,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 4 "scanner.l"
#include <stdio.h>
#include <string.h>
#include "symbol_table.h"
#include "grammar.tab.h"
#include "stack.h"

#define DEFINE 603
#define YY_USER_INIT yylloc.first_line=1;

void count();
void comment();
void comment2();
void comment3();
void trataInclude();
void trataDefine();
void trata_carac(char c);

extern char* TOKEN;
extern symbol_t table;
extern symbol_t typedefs;
extern symbol_t defines;
extern stack tipos[2];
extern symbol_t arquivos;
extern stack nomesArq;
extern stack parenteses;
extern YYLTYPE yylloc;

extern int line;
extern int column;

int ultimoToken = 0;
#line 724 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 45 "scanner.l"

#line 913 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 426 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "scanner.l"
{ count(); comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "scanner.l"
{ count(); comment3(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "scanner.l"
{ count(); trataInclude(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "scanner.l"
{ count(); trataDefine(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "scanner.l"
{ count(); comment2(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "scanner.l"
{ count(); comment2(); unput(';'); column--; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "scanner.l"
{ count(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "scanner.l"
{ count(); ultimoToken = 0; return(AUTO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "scanner.l"
{ count(); ultimoToken = 0; return(BREAK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "scanner.l"
{ count(); ultimoToken = 0; return(CASE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "scanner.l"
{ count(); ultimoToken = 0; return(CHAR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "scanner.l"
{ count(); ultimoToken = 0; return(CONST); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "scanner.l"
{ count(); ultimoToken = 0; return(CONTINUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 60 "scanner.l"
{ count(); ultimoToken = 0; return(DEFAULT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 61 "scanner.l"
{ count(); ultimoToken = 0; return(DO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 62 "scanner.l"
{ count(); ultimoToken = 0; return(DOUBLE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 63 "scanner.l"
{ count(); ultimoToken = 0; return(ELSE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "scanner.l"
{ count(); ultimoToken = 0; return(ENUM); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "scanner.l"
{ count(); ultimoToken = 0; return(EXTERN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "scanner.l"
{ count(); ultimoToken = 0; return(FLOAT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "scanner.l"
{ count(); ultimoToken = 0; 
			  yylloc.first_line = line; 
			  yylloc.first_column = column - yyleng; 
		    	  return(FOR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "scanner.l"
{ count(); ultimoToken = 0; return(GOTO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "scanner.l"
{ count(); ultimoToken = 0; return(IF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "scanner.l"
{ count(); ultimoToken = 0; return(INT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "scanner.l"
{ count(); ultimoToken = 0; return(LONG); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "scanner.l"
{ count(); ultimoToken = 0; return(REGISTER); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "scanner.l"
{ count(); ultimoToken = 0; return(RETURN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "scanner.l"
{ count(); ultimoToken = 0; return(SHORT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "scanner.l"
{ count(); ultimoToken = 0; return(SIGNED); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "scanner.l"
{ count(); ultimoToken = 0; return(SIZEOF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "scanner.l"
{ count(); ultimoToken = 0; return(STATIC); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "scanner.l"
{ count(); ultimoToken = STRUCT; return(STRUCT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 82 "scanner.l"
{ count(); ultimoToken = 0; return(SWITCH); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "scanner.l"
{ count(); ultimoToken = TYPEDEF; return(TYPEDEF); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "scanner.l"
{ count(); ultimoToken = 0; return(UNION); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "scanner.l"
{ count(); ultimoToken = 0; return(UNSIGNED); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "scanner.l"
{ count(); ultimoToken = 0; return(VOID); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "scanner.l"
{ count(); ultimoToken = 0; return(VOLATILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "scanner.l"
{ count(); ultimoToken = 0; return(WHILE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "scanner.l"
{ count(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "scanner.l"
{ count(); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "scanner.l"
{ count();
			  int tipo = check_type();
			  yylloc.first_line = line;
			  yylloc.first_column = column - yyleng; 
			  if (tipo != DEFINE)
			  {
			  	ultimoToken = 0; 
			  	yylval.geral.lexema = (char*)malloc(strlen(yytext)+1);
			  	strcpy(yylval.geral.lexema,yytext);
			  	yylval.geral.token = tipo;
			  	return(tipo);
			  }
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "scanner.l"
{ count(); ultimoToken = 0; return(CONSTANT_INT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "scanner.l"
{ count(); ultimoToken = 0; return(CONSTANT_INT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 108 "scanner.l"
{ count(); ultimoToken = 0; 
			  yylval.geral.lexema = (char*)malloc(strlen(yytext)+1);
			  strcpy(yylval.geral.lexema,yytext);
			  yylval.geral.token = CONSTANT; 
			  return(CONSTANT_INT); }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 114 "scanner.l"
{ count(); ultimoToken = 0; return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 116 "scanner.l"
{ count(); ultimoToken = 0; return(CONSTANT_FLOAT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 117 "scanner.l"
{ count(); ultimoToken = 0; return(CONSTANT_FLOAT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 118 "scanner.l"
{ count(); ultimoToken = 0; return(CONSTANT_FLOAT); }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 120 "scanner.l"
{ count(); if (ultimoToken == STRING_LITERAL) 
				   { }
				   else
				   { 
					ultimoToken = STRING_LITERAL; 
					return(STRING_LITERAL); 
				   }
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 129 "scanner.l"
{ count(); ultimoToken = 0; return(ELLIPSIS); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 130 "scanner.l"
{ count(); ultimoToken = 0; return(RIGHT_ASSIGN);  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 131 "scanner.l"
{ count(); ultimoToken = 0; return(LEFT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 132 "scanner.l"
{ count(); ultimoToken = 0; return(ADD_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "scanner.l"
{ count(); ultimoToken = 0; return(SUB_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "scanner.l"
{ count(); ultimoToken = 0; return(MUL_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "scanner.l"
{ count(); ultimoToken = 0; return(DIV_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "scanner.l"
{ count(); ultimoToken = 0; return(MOD_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "scanner.l"
{ count(); ultimoToken = 0; return(AND_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "scanner.l"
{ count(); ultimoToken = 0; return(XOR_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "scanner.l"
{ count(); ultimoToken = 0; return(OR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "scanner.l"
{ count(); ultimoToken = 0; return(RIGHT_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "scanner.l"
{ count(); ultimoToken = 0; return(LEFT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "scanner.l"
{ count(); ultimoToken = 0; return(INC_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "scanner.l"
{ count(); ultimoToken = 0; return(DEC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "scanner.l"
{ count(); ultimoToken = 0; return(PTR_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "scanner.l"
{ count(); ultimoToken = 0; return(AND_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 146 "scanner.l"
{ count(); ultimoToken = 0; return(OR_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "scanner.l"
{ count(); ultimoToken = 0; return(LE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "scanner.l"
{ count(); ultimoToken = 0; return(GE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "scanner.l"
{ count(); ultimoToken = 0; return(EQ_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "scanner.l"
{ count(); ultimoToken = 0; return(NE_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "scanner.l"
{ count(); ultimoToken = 0; return(';'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 152 "scanner.l"
{ count(); ultimoToken = 0; return('{'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 153 "scanner.l"
{ count(); ultimoToken = 0; return('}'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 154 "scanner.l"
{ count(); ultimoToken = 0; return(','); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 155 "scanner.l"
{ count(); ultimoToken = 0; return(':'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 156 "scanner.l"
{ count(); ultimoToken = 0; return('='); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 157 "scanner.l"
{ count(); ultimoToken = '('; return('('); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 158 "scanner.l"
{ count(); ultimoToken = 0; return(')'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 159 "scanner.l"
{ count(); ultimoToken = 0; return('['); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 160 "scanner.l"
{ count(); ultimoToken = 0; return(']'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 161 "scanner.l"
{ count(); ultimoToken = 0; return('.'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 162 "scanner.l"
{ count(); ultimoToken = 0; return('&'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 163 "scanner.l"
{ count(); ultimoToken = 0; return('!'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 164 "scanner.l"
{ count(); ultimoToken = 0; return('~'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 165 "scanner.l"
{ count(); ultimoToken = 0; return('-'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 166 "scanner.l"
{ count(); ultimoToken = 0; return('+'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 167 "scanner.l"
{ count(); ultimoToken = 0; return('*'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 168 "scanner.l"
{ count(); ultimoToken = 0; return('/'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 169 "scanner.l"
{ count(); ultimoToken = 0; return('%'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 170 "scanner.l"
{ count(); ultimoToken = 0; return('<'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 171 "scanner.l"
{ count(); ultimoToken = 0; return('>'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 172 "scanner.l"
{ count(); ultimoToken = 0; return('^'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 173 "scanner.l"
{ count(); ultimoToken = 0; return('|'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 174 "scanner.l"
{ count(); ultimoToken = 0; return('?'); }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 176 "scanner.l"
{ count(); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 177 "scanner.l"
{ count(); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 179 "scanner.l"
ECHO;
	YY_BREAK
#line 1530 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 290);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 179 "scanner.l"



void comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0)
		trata_carac(c);
		
	trata_carac(c);

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}
	
	trata_carac(c1);
}

void comment2()
{
	char c;
	char antes;

loop2:	while ((c = input()) != '\n' && c != 0)
	{
		trata_carac(c);
		antes = c;
	}
	
	trata_carac(c);

	if (antes == '\\')
		goto loop2;	
		
}

void comment3()
{
	char c;
	char antes;
	char* palavraElse = "endif";
	int i = 0;
	char buf[5];

loop3:  while ((c = input()) != '#' && c != 0)
		trata_carac(c);
		
	trata_carac(c);

	i = 0;
	while (i < 5)
	{
		if ((buf[i] = input()) != palavraElse[i])
		{
			while (i >= 0)
			{
				unput(buf[i]);
				i--;
			}
			goto loop3;
		}
		i++;
	}		
	
	column += 5;
}

void trataInclude()
{
	char c;
	FILE *arq;
	char nomeArq[100];
	int i;
	
	while ((c = input()) != '\"' && c != 0 && c != '<')
		trata_carac(c);
		
	if (c == '<')
	{
		while ((c = input()) != '>' && c!= 0)
			trata_carac(c);
		return;
	}

	i = 0;

	while ((c = input()) != '\"' && c != 0)
		nomeArq[i++] = c;

	nomeArq[i] = '\0';
	
	if (!lookup(arquivos,nomeArq))
	{
		entry_t* entrada = (entry_t*)malloc(sizeof(entry_t));
		entrada->name = nomeArq;
		insert(&arquivos,entrada);
		char* p = malloc(strlen(nomeArq));
		strcpy(p,nomeArq);
		push(&nomesArq,p);
		yyrestart(yyin);
		yyin = fopen(nomeArq,"r");
		line = 1;
		column = 1;
	}
	
	column += i;
}

void trataDefine()
{
	char c,antes;
	FILE *arq;
	char nome[100];
	char valor[100];
	int i;
	
	while ((c = input()) == ' ' || c == '\t')
		trata_carac(c);
		
	trata_carac(c);

	nome[0] = c;
	i = 1;

loop4:	while ((c = input()) != ' ' && c != '\t' && c != '\n')
	{
		if (c == '(')
			push(&parenteses,"(");
		if (c == ')')
			pop(&parenteses);
		nome[i++] = c;
		antes = c;
		trata_carac(c);
	}
	
	trata_carac(c);

	if ((c == '\n') && (antes == '\\'))
	{
		i--;
		goto loop4;
	}

	if (!empty(parenteses))
		goto loop4;

	nome[i] = '\0';

	while ((c = input()) == ' ' || c == '\t')
		trata_carac(c);

	valor[0] = c;
	i = 1;
loop5:	while ((c = input()) != '\n')
	{
		valor[i++] = c;
		antes = c;
		trata_carac(c);
	}
	
	trata_carac(c);

	if ((c == '\n') && (antes == '\\'))
	{
		i--;
		goto loop5;
	}

	valor[i] = '\0';

	entry_t* entrada = (entry_t*)malloc(sizeof(entry_t));
	entrada->name = malloc(strlen(nome));
	strcpy(entrada->name,nome);
	entrada->tipo_str = malloc(strlen(valor));
	strcpy(entrada->tipo_str,valor);
	insert(&defines,entrada);
}

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
		{
			column = 1;
			line++;
		}
		else if (yytext[i] == '\t')
			column += 8 - (column % 8) + 1;
		else
			column++; 
}

void trata_carac(char c)
{
	if (c == '\n')
	{
		column = 1;
		line++;
	}
	else if (c == '\t')
		column += 8 - (column % 8);
	else
		column++;
}

int check_type()
{
	entry_t* entrada;
	int tam,j;

	if ((entrada = lookup(defines,yytext)) != NULL)
	{
		tam = strlen(entrada->tipo_str);
		while (tam != 0)
		{
			unput(entrada->tipo_str[tam-1]);
			tam--;
		}		
		return(DEFINE);
	}

	if ((ultimoToken == STRUCT) || (ultimoToken == '('))
	{
		if (ultimoToken == '(')
		  while (!empty(tipos[0]))
			pop(&tipos[0]);
		return IDENTIFIER;
	}

	if ((lookup(typedefs,yytext)) || (ultimoToken == TYPEDEF))
		return(TYPE_NAME); 

	return(IDENTIFIER);
}

