all:
	make -C stream_original
	make -C stream_one
	make -C stream_patterns
	make -C stream_random
	make -C stream_dynamic

clean:
	make -C stream_original clean
	make -C stream_one clean
	make -C stream_patterns clean
	make -C stream_random clean
	make -C stream_dynamic clean
